import type { StepExecutionContext, StepExecutionResult, StepExecutor } from '@yarub/ai-core';
import type { CapabilityRouter } from '@yarub/ai-core';
import type { ImageProvider } from '@yarub/providers';
import type { Capability } from '@yarub/shared';
import type { ObjectStorage } from '@yarub/storage';
import { assertSufficientCredits, assertWithinQuota, recordUsage, type Quotas } from '../services/usage.js';

/**
 * Image steps. Generated bytes go straight to object storage and the step
 * output is the storage key, so large binaries never travel through the job
 * checkpoint table.
 */
export class ImageExecutor implements StepExecutor {
  constructor(
    private readonly router: CapabilityRouter,
    private readonly storage: ObjectStorage,
    private readonly userId: string,
    private readonly projectId: string,
    private readonly quotas: Quotas,
    private readonly creditsEnabled = false,
  ) {}

  supports(capability: Capability): boolean {
    return capability === 'image.generate' || capability === 'image.edit';
  }

  async execute(ctx: StepExecutionContext): Promise<StepExecutionResult> {
    await assertWithinQuota(this.userId, ctx.step.capability, 1, this.quotas);
    await assertSufficientCredits(this.userId, ctx.step.capability, 1, this.creditsEnabled);

    const resolved = await this.router.route<ImageProvider>(ctx.step.capability, ctx.language);
    if (!resolved.ok) throw resolved.error;
    const provider = resolved.value;

    const images = await provider.generate({
      prompt: ctx.prompt,
      width: 1024,
      height: 1024,
      count: 1,
      signal: ctx.signal,
    });

    const first = images[0];
    if (!first) throw new Error('Image provider returned no image');

    const key = `projects/${this.projectId}/assets/${ctx.jobId}-${ctx.step.id}.png`;
    await this.storage.put(key, first.bytes, first.mime);

    await recordUsage({
      userId: this.userId,
      jobId: ctx.jobId,
      capability: ctx.step.capability,
      providerId: first.providerId,
      units: images.length,
    });

    return { outputRef: key, providerId: first.providerId, units: images.length };
  }
}
